import msgImage1 from "../../assets/images/church2.jpg";

export const items = [
  {
    id: 1,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 1",
    // isAvailable: true,
  },
  {
    id: 2,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 1",
  },
  {
    id: 3,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 1",
  },
  {
    id: 4,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 1",
  },
  {
    id: 5,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 1",
  },
  {
    id: 6,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 1",
  },
  {
    id: 7,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 2",
  },
  {
    id: 8,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 2",
  },
  {
    id: 9,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 2",
  },
  {
    id: 10,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 2",
  },
  {
    id: 11,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 2",
  },
  {
    id: 12,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 2",
  },
  {
    id: 13,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 3",
  },
  {
    id: 14,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 3",
  },
  {
    id: 14,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 3",
  },
  {
    id: 16,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 3",
  },
  {
    id: 17,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 3",
  },
  {
    id: 18,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 3",
  },
  {
    id: 19,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 4",
  },
  {
    id: 20,
    img: msgImage1,
    title: "OUR NEXT GUEST",
    heading: " Burn The Ships - Week 4",
  },
];
