export {default as Home} from "./home/Home"
export {default as Contact} from "./contact/Contact"
export {default as Service} from "./service/Service"
export {default as About} from "./about/About"
export {default as Jobs} from "./jobs/Jobs"
export {default as Give} from "./give/Give"
export {default as NotFound} from "./notFound/NotFound"
